apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/blakepettersson/kargo-helm.git
          checkout:
          - fromFreight: true
            path: ./src
          - branch: stage/dev
            create: true
            path: ./out

      - uses: git-clear
        config:
          path: ./out

      - uses: copy
        config:
          inPath: ./src/base/feature-flags.yaml
          outPath: ./out/env/dev/feature-flags.yaml

      - uses: copy
        config:
          inPath: ./src/env/dev/values.yaml
          outPath: ./out/env/dev/values.yaml

      - uses: copy
        config:
          inPath: ./src/charts
          outPath: ./out/charts

      - uses: helm-update-image
        as: update-image
        config:
          path: ./out/env/dev/values.yaml
          images:
            - image: ghcr.io/blakepettersson/guestbook
              key: image.tag
              value: Tag

      # Commit the changes to the Git repository.
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image

      # Push the changes to the Git repository.
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/dev

      - uses: argocd-update
        config:
          apps:
          - name: kargo-helm-dev
            sources:
            - repoURL: https://github.com/blakepettersson/kargo-helm.git
              desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - dev
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/blakepettersson/kargo-helm.git
            checkout:
              - fromFreight: true
                path: ./src
              - branch: stage/staging
                create: true
                path: ./out

        - uses: git-clear
          config:
            path: ./out

        - uses: copy
          config:
            inPath: ./src/base/feature-flags.yaml
            outPath: ./out/env/staging/feature-flags.yaml

        - uses: copy
          config:
            inPath: ./src/env/staging/values.yaml
            outPath: ./out/env/staging/values.yaml

        - uses: copy
          config:
            inPath: ./src/charts
            outPath: ./out/charts

        - uses: helm-update-image
          as: update-image
          config:
            path: ./out/env/staging/values.yaml
            images:
              - image: ghcr.io/blakepettersson/guestbook
                key: image.tag
                value: Tag

        # Commit the changes to the Git repository.
        - uses: git-commit
          as: commit
          config:
            path: ./out
            messageFromSteps:
              - update-image

        # Push the changes to the Git repository.
        - uses: git-push
          config:
            path: ./out
            targetBranch: stage/staging

        - uses: argocd-update
          config:
            apps:
              - name: kargo-helm-staging
                sources:
                  - repoURL: https://github.com/blakepettersson/kargo-helm.git
                    desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
    - origin:
        kind: Warehouse
        name: features
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/blakepettersson/kargo-helm.git
            checkout:
              - fromFreight: true
                path: ./src
              - branch: stage/prod
                create: true
                path: ./out

        - uses: git-clear
          config:
            path: ./out

        - uses: copy
          config:
            inPath: ./src/base/feature-flags.yaml
            outPath: ./out/env/prod/feature-flags.yaml

        - uses: copy
          config:
            inPath: ./src/env/prod/values.yaml
            outPath: ./out/env/prod/values.yaml

        - uses: copy
          config:
            inPath: ./src/charts
            outPath: ./out/charts

        - uses: helm-update-image
          as: update-image
          config:
            path: ./out/env/prod/values.yaml
            images:
              - image: ghcr.io/blakepettersson/guestbook
                key: image.tag
                value: Tag

        # Commit the changes to the Git repository.
        - uses: git-commit
          as: commit
          config:
            path: ./out
            messageFromSteps:
              - update-image

        # Push the changes to the Git repository.
        - uses: git-push
          config:
            path: ./out
            targetBranch: stage/prod

        - uses: argocd-update
          config:
            apps:
              - name: kargo-helm-prod
                sources:
                  - repoURL: https://github.com/blakepettersson/kargo-helm.git
                    desiredCommitFromStep: commit
