apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - list:
      elements:
        - stage: dev
        - stage: staging
        - stage: prod
  template:
    metadata:
      name: kargo-helm-{{.stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm:{{.stage}}
    spec:
      destination:
        namespace: kargo-helm-{{.stage}}
        name: demo
      project: kargo-helm
      source:
        path: charts/guestbook
        repoURL: https://github.com/blakepettersson/kargo-helm.git
        targetRevision: stage/{{.stage}}
        helm:
          valueFiles:
          - "/env/{{.stage}}/values.yaml"
          - "/env/{{.stage}}/feature-flags.yaml"
